### ISSUE TITLE
Implement Auth header token for pulling of schema GraphQL API

### ISSUE THREAD

**Issue by ImanX** [suparngp/kotlin-multiplatform-projects#69]
I'm facing to an issue that I'm working with a GraphQL API which it need to Authorization header for pulling schema but `suparnaturalGraphQl` don't have any property but func for set auth token.

**Comment by suparngp** [comment]
It allows you to use any transport that you want and makes no assumption whatsoever about your client.  Check out these examples

https://kmpdocs.suparnatural.com/graphql/concepts.html#fetcher

If this is not enough for your use case, let me know what would be a good approach to solve your use case?

**Comment by suparngp** [comment]
Oh, I get it now. You are referring to the plugin. Ok, I ll add support for this.

**Comment by suparngp** [comment]
New plugin v1.0.11 is published.

Usage -> https://kmpdocs.suparnatural.com/graphql/installation.html#configure-gradle-plugin

**Comment by ImanX** [comment]
Thank u dude, can u set open source plugin?
