### ISSUE TITLE
[ENHANCEMENT] Support Kotlin 1.4

### ISSUE THREAD

**Issue by battery-staple** [suparngp/kotlin-multiplatform-projects#76]
I've been using suparnatural-fs before with Kotlin 1.3, and it's worked great. However, I've updated my project to use Kotlin 1.4, so of course this library no longer works.

There are very few breaking changes in Kotlin 1.4, so essentially all that should be needed to update is a recompile with updated build settings.

Thank you!

**Comment by suparngp** [comment]
Just an update, I am in the middle of upgrading. For some reason, Gradle V6 is throwing bunch of compilation issues in the gradle plugin I wrote to simplify the build process. I ll post an update as soon as it is done.

**Comment by suparngp** [comment]
I made a lot of progress in the last week. Essentially, I rewrote the build system from scratch with hierarchical structure and a couple of other things. I have published `fs:1.0.12` temporarily. There are no API changes. Please let me know if it is working. I ll finish the remaining libs soon.

**Comment by battery-staple** [comment]
Great! I'll try it out soon.

**Comment by suparngp** [comment]
Merged with #79
