### ISSUE TITLE
[BUG] Why doesn't Kotlin Multiplatform Projects work on Android Studio 4.0.1

### ISSUE THREAD

**Issue by shyamalschandra** [suparngp/kotlin-multiplatform-projects#77]
**Describe the bug**
I don't get the option for iOS in Android Studio 4.0.1.

**To Reproduce**
1. Download latest Android Studio.
2. Download the plugin for KMP.
3. Create a new project for KMP.

**Expected behavior**
It should allow you to have an iOS project.

**Stacktrace**
n/a

**Version**
0.1.0

**Platforms affected:**
- iOS [ X ]
- Android [ X ]
- JVM [ X ]

**Additional context**

**Comment by suparngp** [comment]
I don't understand what you mean by "option for iOS in Android Studio". What option are we talking about here?

**Comment by shyamalschandra** [comment]
@suparngp : That's what I meant...nothing else.  What is your understanding?

**Comment by shyamalschandra** [comment]
There isn't any "Configure Activity" page in the wizard for KMM that allows one to select the iOS Application name.  Has anything changed?

Below is the screenshot of the wizard step on the kotlinlang.org [website](https://kotlinlang.org/docs/mobile/create-first-app.html):

![](https://kotlinlang.org/docs/mobile/images/kmm-project-wizard-3.png)

**Comment by suparngp** [comment]
@shyamalschandra are you trying to open this repository on Android Studio? I have never tested that because I only use IntelliJ. Also, I don't think that you can create a new project by directly cloning this repository, you have to use the published artifacts in your own project. 

And honestly I don't think I still understand what you are trying to do. 😀

**Comment by shyamalschandra** [comment]
<img width="1345" alt="Screen Shot 2020-10-07 at 5 08 45 AM" src="https://user-images.githubusercontent.com/9545735/95317791-42299680-085b-11eb-917d-2a32882c64ea.png">

I opened Android Studio 4.0.1 on MacOS Catalina, click on the menu item "Android Studio" -> "Preferences" -> Click on "Plugins" on the left pane -> Type in "Kotlin Multiplatform Mobile" and see the plugin come in the results.  Then, click "Install" on the right side of the right pane and there it goes and installs.

Thus, it takes you to the screenshot above.

What is not clear about this?  Android Studio 4.0.1 says that it is installing KMM version 0.1.3-release-54-Studio4.0 from Oct 02, 2020.  I am not taking the source code from the github repository.  Do you understand now, @suparngp?

**Comment by suparngp** [comment]
Owkay... and how is this bug related to the code in this repository? 🤔

**Comment by shyamalschandra** [comment]
Because the source code turns into the package that is downloaded as a plugin inside the Android Studio 4.0.1.

Any further questions, @suparngp!

**Comment by suparngp** [comment]
But I am not the author of that plugin. So what exactly are you expecting me to do here? Shouldn't you open this against Jetbrain's Youtrack project?

**Comment by shyamalschandra** [comment]
Who's the contributor here?

https://github.com/suparngp/kotlin-multiplatform-projects/graphs/contributors?from=2019-06-23&to=2020-10-08&type=a

Please let me know and clarify.  Is there some fork that is controlled by the JetBrains people?

https://github.com/suparngp/kotlin-multiplatform-projects/network/members

**Comment by suparngp** [comment]
@shyamalschandra 

> Because the source code turns into the package that is downloaded as a plugin inside the Android Studio 4.0.1.
Yes, you are right, some source code definitely turns in the the package and makes that plugin. But not this code. Some other code, not this code.

> Who's the contributor here?
Yep, You are right again. ⚡ That includes me.

> Please let me know and clarify. Is there some fork that is controlled by the JetBrains people?
I have no idea, as you can see the list of forks too.

If you have an issue related to the Kotlin Multiplatform Mobile plugin, this is not the right place. At least, I don't think so. This is what I have been trying to explain.

1. The Kotlin Multiplatform Mobile plugin you mentioned in the screenshot is an official Jetbrains plugin. This repo contains "Libraries for Kotlin Multiplatform". This repository has nothing to do with that plugin. Start with this page and tell me what links you back to this repo https://plugins.jetbrains.com/plugin/14936-kotlin-multiplatform-mobile
2. I am not the author of that plugin. I have no idea what gave you that impression. Seriously, I'd like to know. 😮 
3. Jetbrains tracks all issues related to Kotlin here  as far as I know -> https://youtrack.jetbrains.com/issues/KT?q=project:%20Kotlin
So try opening an issue and see what they have to say?

I hope this helps.

**Comment by suparngp** [comment]
@shyamalschandra hopefully your issue is/will be resolved with JB. I am closing now.
