### ISSUE TITLE
[PLATFORM REQUEST] nodeJS (fs)

### ISSUE THREAD

**Issue by DetachHead** [suparngp/kotlin-multiplatform-projects#80]
Put an `x` in the desired checkboxes

**Project**
- cache [ ]
- fs [x]
- concurrency [ ]

**New Platform**
- iOS [ ]
- Android [ ]
- JVM [ ]
- macOS [ ]
- other [nodeJS]

**Are you committed to support this new platform all by yourself?**
- Yes, I want to own it [X]
- No, I do not have the resources [ ]

This is just to ensure that there is some one who can actively support the platform in the future. Feel free to mark `No`.

**Motivation**
i primarily use kotlin multiplatform for jvm & js targets. would be nice to have a filesystem library that works on both of them

**Comment by DetachHead** [comment]
i'd like to try to implement this myself but i'm having trouble wrapping my head around how this project is set up. there doesn't seem to be `actual` definitions for most of the `FileSystem` members in the `jvmMain` target. seems to use the `iosMain` target instead when i import it to my own project's `jvmMain` source set?

**Comment by DetachHead** [comment]
https://github.com/DetachHead/kotlin-multiplatform-projects

**Comment by suparngp** [comment]
Thanks! Go for it
