### ISSUE TITLE
Move away from Bintray

### ISSUE THREAD

**Issue by moopat** [suparngp/kotlin-multiplatform-projects#93]
Starting May 1st 2021 [packages can no longer be downloaded from Bintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). 

Please find an alternative way to distribute the packages so software that depends on this project can still be built five days from now. Let me know if I can help.

**Comment by FarshidRoohi** [comment]
hi, please move to Maven.
can't resolve library and have a big problem
thank you

@suparngp

**Comment by ImanX** [comment]
Our product depends of your project and it faced out this issue, You should acting out to migration to other distribute.
Many Thanks @suparngp.

**Comment by suparngp** [comment]
Thanks for opening this issue. I wasn't aware of this change. Looking into options.

**Comment by suparngp** [comment]
In progress https://issues.sonatype.org/browse/OSSRH-68542

**Comment by FarshidRoohi** [comment]
Hi, did you find an option?

@suparngp

**Comment by ImanX** [comment]
What's up?! 😁😁

**Comment by FarshidRoohi** [comment]
@suparngp

**Comment by suparngp** [comment]
I am just waiting for someone to on OSS Jira to approve access. Everything else is in place. Almost there.

**Comment by suparngp** [comment]
I was able to publish the first version of utilities package. Now waiting for someone on the JIRA ticket to sync the repo to maven central.


In the meantime, please leave a 👍 if you want me to bump the version or a 👎 if you want it to be the same as the last version published on the Bintray.

Thank you for the patience.

**Comment by ImanX** [comment]
Hey @suparngp You have to close and next release  after uploaded artifact in sonatype panel, please check it quickly dude.

**Comment by suparngp** [comment]
@ImanX and what gives the impression that I didn't already do that, dude? 🙂

Anyways, the released repo is now synced to maven central. I ll publish the rest of the packages today.

**Comment by suparngp** [comment]
All packages are now available on maven under `com.suparnatural.kotlin`.

https://repo1.maven.org/maven2/com/suparnatural/kotlin/

**Comment by ImanX** [comment]
> All packages are now available on maven under `com.suparnatural.kotlin`.
> 
> https://repo1.maven.org/maven2/com/suparnatural/kotlin/

Thank you dude ❤️
